### ISSUE TITLE
Unable to run index.html locally

### ISSUE THREAD

**Issue by Apis035** [lwd-temp/blue-archive-spine#6]
Is it possible to run this locally on my pc, without needing to use GitHub action and looking through GitHub pages?
I've tried cloning and setup this, but when opening index.html all I see in just the left pane with empty "Select Model" list, not showing anything.

Thought I did something wrong on my Windows so I tried setup this on a Ubuntu VM but the result is the same.

Any help?

**Comment by Apis035** [comment]
Never mind, I found this https://github.com/respectZ/blue-archive-spine/issues/22 and I was able to run this with Nginx.

But still, the instruction on README wasn't clear. Should 've mentioned to run this through a web server.

**Comment by SunsetMkt** [comment]
Sorry.

https://github.com/lwd-temp/blue-archive-spine/commit/7906e2703d36047382b3755f270bdafeb0406d1b
